version_file: pyproject.toml
version_pattern: version\s*=\s*["']([^"']+)["']

changelog_file: CHANGELOG.md
changelog_pattern: '## \[([^\]]+)\]'

git:
  main_branch: main
  commit_message: "chore: release version {version}"
  tag_message: "Release version {version}"
  tag_name: "v{version}"

release_notes:
  enabled: true
  from_latest_tag: true

pre_release_checks:
  - check_git_clean
  - check_branch
  - run_tests
  - check_version_bumped
  - check_changelog

build:
  commands:
    - python -m build

publish:
  repository: pypi
  build_command: python -m build
  dist_dir: dist/ 